using System.Text;

namespace PgSchemaExporter.Core.Migration;

/// <summary>
/// The result of comparing two exported schema directories: an ordered set of
/// forward (<see cref="Up"/>) and rollback (<see cref="Down"/>) statements.
/// </summary>
public sealed class MigrationScript
{
    public IReadOnlyList<MigrationStatement> Up { get; init; } = [];
    public IReadOnlyList<MigrationStatement> Down { get; init; } = [];

    public bool HasChanges => Up.Count > 0;

    public bool HasDestructiveChanges => Up.Any(x => x.IsDestructive) || Down.Any(x => x.IsDestructive);

    /// <summary>True when any statement must run outside a transaction (e.g. concurrent index builds).</summary>
    public bool HasConcurrentStatements => Up.Any(x => x.RunsOutsideTransaction) || Down.Any(x => x.RunsOutsideTransaction);

    public string RenderUp(bool safe) => RenderUp(MigrationRenderOptions.ForSafe(safe));

    public string RenderDown(bool safe) => RenderDown(MigrationRenderOptions.ForSafe(safe));

    public string RenderUp(MigrationRenderOptions options)
        => Render("Up migration (apply changes)", Up, options, concurrentBeforeTransaction: false);

    public string RenderDown(MigrationRenderOptions options)
        => Render("Down migration (roll back changes)", Down, options, concurrentBeforeTransaction: true);

    private static string Render(
        string title,
        IReadOnlyList<MigrationStatement> statements,
        MigrationRenderOptions options,
        bool concurrentBeforeTransaction)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- " + title);
        sb.AppendLine("-- Generated by PgSchemaExporter. Review before running in production.");
        sb.AppendLine();

        if (statements.Count == 0)
        {
            sb.AppendLine("-- No changes detected.");
            return sb.ToString();
        }

        AppendSessionSettings(sb, options);

        var transactional = statements.Where(s => !s.RunsOutsideTransaction).ToList();
        var concurrent = statements.Where(s => s.RunsOutsideTransaction).ToList();

        void RenderConcurrent()
        {
            if (concurrent.Count == 0)
                return;

            sb.AppendLine("-- The following statements run OUTSIDE a transaction (cannot be wrapped in BEGIN/COMMIT).");
            foreach (var statement in concurrent)
                AppendStatement(sb, statement, options.Safe);
        }

        void RenderTransactional()
        {
            if (transactional.Count == 0)
                return;

            sb.AppendLine("BEGIN;");
            sb.AppendLine();

            foreach (var statement in transactional)
                AppendStatement(sb, statement, options.Safe);

            sb.AppendLine("COMMIT;");
        }

        if (concurrentBeforeTransaction)
        {
            RenderConcurrent();
            RenderTransactional();
        }
        else
        {
            RenderTransactional();
            RenderConcurrent();
        }

        return sb.ToString();
    }

    private static void AppendSessionSettings(StringBuilder sb, MigrationRenderOptions options)
    {
        var wrote = false;

        if (!string.IsNullOrWhiteSpace(options.LockTimeout))
        {
            sb.AppendLine($"SET lock_timeout = '{options.LockTimeout}';");
            wrote = true;
        }

        if (!string.IsNullOrWhiteSpace(options.StatementTimeout))
        {
            sb.AppendLine($"SET statement_timeout = '{options.StatementTimeout}';");
            wrote = true;
        }

        if (wrote)
            sb.AppendLine();
    }

    private static void AppendStatement(StringBuilder sb, MigrationStatement statement, bool safe)
    {
        if (!string.IsNullOrWhiteSpace(statement.Comment))
            sb.AppendLine("-- " + statement.Comment);

        if (safe && statement.IsDestructive)
        {
            sb.AppendLine("-- DESTRUCTIVE: review and enable manually.");
            foreach (var line in SplitLines(statement.Sql))
                sb.AppendLine("-- " + line);
        }
        else
        {
            sb.AppendLine(statement.Sql.TrimEnd());
        }

        sb.AppendLine();
    }

    private static IEnumerable<string> SplitLines(string text)
        => text.Replace("\r\n", "\n").TrimEnd('\n').Split('\n');
}
