using System.Text;

namespace PgSchemaExporter.Core.Migration;

/// <summary>
/// The result of comparing two exported schema directories: an ordered set of
/// forward (<see cref="Up"/>) and rollback (<see cref="Down"/>) statements.
/// </summary>
public sealed class MigrationScript
{
    public IReadOnlyList<MigrationStatement> Up { get; init; } = [];
    public IReadOnlyList<MigrationStatement> Down { get; init; } = [];

    public bool HasChanges => Up.Count > 0;

    public bool HasDestructiveChanges => Up.Any(x => x.IsDestructive) || Down.Any(x => x.IsDestructive);

    public string RenderUp(bool safe) => Render("Up migration (apply changes)", Up, safe);

    public string RenderDown(bool safe) => Render("Down migration (roll back changes)", Down, safe);

    private static string Render(string title, IReadOnlyList<MigrationStatement> statements, bool safe)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- " + title);
        sb.AppendLine("-- Generated by PgSchemaExporter. Review before running in production.");
        sb.AppendLine();

        if (statements.Count == 0)
        {
            sb.AppendLine("-- No changes detected.");
            return sb.ToString();
        }

        sb.AppendLine("BEGIN;");
        sb.AppendLine();

        foreach (var statement in statements)
        {
            if (!string.IsNullOrWhiteSpace(statement.Comment))
                sb.AppendLine("-- " + statement.Comment);

            if (safe && statement.IsDestructive)
            {
                sb.AppendLine("-- DESTRUCTIVE: review and enable manually.");
                foreach (var line in SplitLines(statement.Sql))
                    sb.AppendLine("-- " + line);
            }
            else
            {
                sb.AppendLine(statement.Sql.TrimEnd());
            }

            sb.AppendLine();
        }

        sb.AppendLine("COMMIT;");
        return sb.ToString();
    }

    private static IEnumerable<string> SplitLines(string text)
        => text.Replace("\r\n", "\n").TrimEnd('\n').Split('\n');
}
