namespace PgSchemaExporter.Core.Output;

public sealed class DeployScriptWriter
{
    public async Task WriteAsync(
        string outputDirectory,
        IReadOnlyList<string> relativeSqlFiles,
        CancellationToken cancellationToken = default)
    {
        var deployPath = Path.Combine(outputDirectory, "deploy.sql");

        var lines = new List<string>
        {
            "-- Auto-generated by PostgreSQL Git-Native Schema Exporter",
            "-- Run from this directory with:",
            "-- psql -d <database> -f deploy.sql",
            "",
            "\\set ON_ERROR_STOP on",
            ""
        };

        foreach (var file in relativeSqlFiles)
            lines.Add($@"\i {file}");

        await File.WriteAllLinesAsync(deployPath, lines, cancellationToken);
    }
}
