namespace PgSchemaExporter.Core.Output;

public sealed class ReadmeWriter
{
    public async Task WriteAsync(
        string outputDirectory,
        CancellationToken cancellationToken = default)
    {
        var path = Path.Combine(outputDirectory, "README.md");

        var content = """
# PostgreSQL Schema Export

This folder was generated by PostgreSQL Git-Native Schema Exporter v0.9.0.

## How to apply the schema

```bash
psql -d <database> -f deploy.sql
```

## Important files

- `deploy.sql` - ordered execution script for the entire export
- `dependencies.json` - dependency-aware manifest used to explain file ordering
- `README.md` - this guide

## Structure

- `extensions/`
- `schemas/`
- `types/`
- `sequences/`
- `tables/`
- `constraints/`
- `indexes/`
- `functions/`
- `views/`
- `triggers/`
- `policies/`
- `comments/`
- `grants/`
- `misc/`

## Notes

The deployment order is derived from a dependency graph so that tables, views, functions, and related objects are applied in a safe order.
""";

        await File.WriteAllTextAsync(path, content, cancellationToken);
    }
}
