namespace PgSchemaExporter.Core.Output;

public sealed class ReadmeWriter
{
    public async Task WriteAsync(
        string outputDirectory,
        CancellationToken cancellationToken = default)
    {
        var path = Path.Combine(outputDirectory, "README.md");

        var content = """
# PostgreSQL Schema Export

This folder was generated by PostgreSQL Git-Native Schema Exporter.

## Run

```bash
psql -d <database> -f deploy.sql
```

## Files

- `deploy.sql` - generated execution script
- `dependencies.json` - dependency-aware manifest used to explain ordering

## Structure

- `extensions/`
- `schemas/`
- `types/`
- `sequences/`
- `tables/`
- `constraints/`
- `indexes/`
- `functions/`
- `views/`
- `triggers/`
- `policies/`
- `comments/`
- `grants/`
- `misc/`
""";

        await File.WriteAllTextAsync(path, content, cancellationToken);
    }
}
