using PgSchemaExporter.Core.Models;
using PgSchemaExporter.Core.Scripting;
using Xunit;

namespace PgSchemaExporter.Tests;

public class TableScriptGeneratorTests
{
    [Fact]
    public void Generate_IncludesIdentityAndCollationClauses()
    {
        var table = new DbTable
        {
            Schema = "public",
            Name = "users",
            Columns =
            [
                new DbColumn
                {
                    Name = "id",
                    DataType = "integer",
                    IsNullable = false,
                    IsIdentity = true,
                    IdentityGeneration = "BY DEFAULT",
                    Collation = "de_DE"
                }
            ]
        };

        var generator = new TableScriptGenerator();
        var sql = generator.Generate(table);

        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", sql);
        Assert.Contains("COLLATE", sql);
    }

    [Fact]
    public void Generate_EmitsValidInheritsAndTablespaceClauses()
    {
        var table = new DbTable
        {
            Schema = "public",
            Name = "audit_events",
            Columns = [new DbColumn { Name = "id", DataType = "integer", IsNullable = false }],
            Tablespace = "fastdisk",
            InheritsFrom = "public.base_event",
            IsUnlogged = true
        };

        var generator = new TableScriptGenerator();
        var sql = generator.Generate(table);

        // Modifier must be part of the CREATE statement, not appended after the closing paren.
        Assert.Contains("CREATE UNLOGGED TABLE", sql);
        Assert.Contains("INHERITS (\"public\".\"base_event\")", sql);
        Assert.Contains("TABLESPACE \"fastdisk\"", sql);

        // The clauses must appear before the terminating semicolon (i.e. inside the statement).
        var clauseIndex = sql.IndexOf("TABLESPACE", StringComparison.Ordinal);
        var semicolonIndex = sql.IndexOf(';');
        Assert.True(clauseIndex < semicolonIndex);
    }

    [Fact]
    public void Generate_EmitsPartitionByClauseForPartitionedParent()
    {
        var table = new DbTable
        {
            Schema = "public",
            Name = "events",
            Columns = [new DbColumn { Name = "created_at", DataType = "timestamp", IsNullable = false }],
            PartitionKey = "RANGE (created_at)"
        };

        var sql = new TableScriptGenerator().Generate(table);

        Assert.Contains("PARTITION BY RANGE (created_at)", sql);
        var clauseIndex = sql.IndexOf("PARTITION BY", StringComparison.Ordinal);
        Assert.True(clauseIndex < sql.IndexOf(';'));
    }

    [Fact]
    public void Generate_EmitsPartitionOfChildAsCommentNotInvalidDdl()
    {
        var table = new DbTable
        {
            Schema = "public",
            Name = "events_2024",
            Columns = [new DbColumn { Name = "id", DataType = "integer", IsNullable = false }],
            PartitionOf = "public.events"
        };

        var sql = new TableScriptGenerator().Generate(table);

        // No bare "PARTITION OF" statement (would be invalid without FOR VALUES); only a comment.
        Assert.Contains("-- PARTITION OF \"public\".\"events\"", sql);
        Assert.DoesNotContain(") PARTITION OF", sql);
    }
}
